11:15:20 PM: DEBUG [logger_base.py:13] Message level: DEBUG
11:15:20 PM: INFO [logger_base.py:14] Message level: INFO
11:15:20 PM: WARNING [logger_base.py:15] Message level: WARNING
11:15:20 PM: ERROR [logger_base.py:16] Message level: ERROR
11:15:20 PM: CRITICAL [logger_base.py:17] Message level: CRITICAL
11:21:15 PM: CRITICAL [task_list_models.py:19] MONGODB_USER variable not found
11:24:12 PM: CRITICAL [task_list_models.py:19] MONGODB_USER variable not found
10:34:12 PM: INFO [_internal.py:96] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
10:34:12 PM: INFO [_internal.py:96] [33mPress CTRL+C to quit[0m
10:34:12 PM: INFO [_internal.py:96]  * Restarting with stat
10:34:13 PM: WARNING [_internal.py:96]  * Debugger is active!
10:34:13 PM: INFO [_internal.py:96]  * Debugger PIN: 108-735-802
10:35:59 PM: INFO [_internal.py:96] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
10:35:59 PM: INFO [_internal.py:96] [33mPress CTRL+C to quit[0m
10:35:59 PM: INFO [_internal.py:96]  * Restarting with stat
10:36:00 PM: WARNING [_internal.py:96]  * Debugger is active!
10:36:00 PM: INFO [_internal.py:96]  * Debugger PIN: 108-735-802
07:51:04 PM: WARNING [logger_base.py:15] Message level: WARNING
07:51:04 PM: ERROR [logger_base.py:16] Message level: ERROR
07:51:04 PM: CRITICAL [logger_base.py:17] Message level: CRITICAL
07:51:29 PM: DEBUG [logger_base.py:13] Message level: DEBUG
07:51:29 PM: INFO [logger_base.py:14] Message level: INFO
07:51:29 PM: WARNING [logger_base.py:15] Message level: WARNING
07:51:29 PM: ERROR [logger_base.py:16] Message level: ERROR
07:51:29 PM: CRITICAL [logger_base.py:17] Message level: CRITICAL
07:55:15 PM: CRITICAL [task_list_models.py:33] Failed to connect to the database: database names cannot contain the character ' '
07:55:35 PM: CRITICAL [task_list_models.py:33] Failed to connect to the database: database names cannot contain the character ' '
07:58:12 PM: INFO [_internal.py:96] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
07:58:12 PM: INFO [_internal.py:96] [33mPress CTRL+C to quit[0m
07:58:12 PM: INFO [_internal.py:96]  * Restarting with stat
07:58:13 PM: WARNING [_internal.py:96]  * Debugger is active!
07:58:13 PM: INFO [_internal.py:96]  * Debugger PIN: 133-926-406
08:02:27 PM: INFO [_internal.py:96] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
08:02:27 PM: INFO [_internal.py:96] [33mPress CTRL+C to quit[0m
08:02:27 PM: INFO [_internal.py:96]  * Restarting with stat
08:02:27 PM: WARNING [_internal.py:96]  * Debugger is active!
08:02:27 PM: INFO [_internal.py:96]  * Debugger PIN: 133-926-406
08:04:08 PM: INFO [_internal.py:96]  * Detected change in '/home/yoaddan/RepositoriosDistribuidos/proyecto_backend/TASKLIST_API/TaskListAPI/models/task_list_models.py', reloading
08:04:09 PM: INFO [_internal.py:96]  * Restarting with stat
08:04:10 PM: WARNING [_internal.py:96]  * Debugger is active!
08:04:10 PM: INFO [_internal.py:96]  * Debugger PIN: 133-926-406
08:07:29 PM: INFO [_internal.py:96]  * Detected change in '/home/yoaddan/RepositoriosDistribuidos/proyecto_backend/TASKLIST_API/TaskListAPI/app.py', reloading
08:07:29 PM: INFO [_internal.py:96]  * Restarting with stat
08:07:30 PM: WARNING [_internal.py:96]  * Debugger is active!
08:07:30 PM: INFO [_internal.py:96]  * Debugger PIN: 133-926-406
08:10:53 PM: INFO [_internal.py:96]  * Detected change in '/home/yoaddan/RepositoriosDistribuidos/proyecto_backend/TASKLIST_API/TaskListAPI/app.py', reloading
08:10:53 PM: INFO [_internal.py:96]  * Restarting with stat
08:10:54 PM: WARNING [_internal.py:96]  * Debugger is active!
08:10:54 PM: INFO [_internal.py:96]  * Debugger PIN: 133-926-406
08:13:46 PM: INFO [_internal.py:96]  * Detected change in '/home/yoaddan/RepositoriosDistribuidos/proyecto_backend/TASKLIST_API/TaskListAPI/services/task_list_services.py', reloading
08:13:47 PM: INFO [_internal.py:96]  * Restarting with stat
08:13:47 PM: WARNING [_internal.py:96]  * Debugger is active!
08:13:47 PM: INFO [_internal.py:96]  * Debugger PIN: 133-926-406
08:15:12 PM: INFO [_internal.py:96]  * Detected change in '/home/yoaddan/RepositoriosDistribuidos/proyecto_backend/TASKLIST_API/TaskListAPI/app.py', reloading
08:15:12 PM: INFO [_internal.py:96]  * Restarting with stat
08:15:13 PM: WARNING [_internal.py:96]  * Debugger is active!
08:15:13 PM: INFO [_internal.py:96]  * Debugger PIN: 133-926-406
08:16:25 PM: INFO [_internal.py:96]  * Detected change in '/home/yoaddan/RepositoriosDistribuidos/proyecto_backend/TASKLIST_API/TaskListAPI/app.py', reloading
08:16:26 PM: INFO [_internal.py:96]  * Restarting with stat
08:16:26 PM: WARNING [_internal.py:96]  * Debugger is active!
08:16:26 PM: INFO [_internal.py:96]  * Debugger PIN: 133-926-406
08:19:52 PM: CRITICAL [task_list_services.py:30] Error fetching all task lists from the database: 'Collection' object is not iterable
08:19:52 PM: ERROR [task_list_routes.py:25] Error fetching data from the database: Object of type Response is not JSON serializable
Traceback (most recent call last):
  File "/home/yoaddan/RepositoriosDistribuidos/proyecto_backend/TASKLIST_API/TaskListAPI/routes/task_list_routes.py", line 23, in get_task_lists
    return jsonify(self.task_lists), 200
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yoaddan/.local/lib/python3.11/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yoaddan/.local/lib/python3.11/site-packages/flask/json/provider.py", line 215, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=self.mimetype
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yoaddan/.local/lib/python3.11/site-packages/flask/json/provider.py", line 180, in dumps
    return json.dumps(obj, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/usr/lib64/python3.11/json/encoder.py", line 202, in encode
    chunks = list(chunks)
             ^^^^^^^^^^^^
  File "/usr/lib64/python3.11/json/encoder.py", line 430, in _iterencode
    yield from _iterencode_list(o, _current_indent_level)
  File "/usr/lib64/python3.11/json/encoder.py", line 326, in _iterencode_list
    yield from chunks
  File "/usr/lib64/python3.11/json/encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "/home/yoaddan/.local/lib/python3.11/site-packages/flask/json/provider.py", line 120, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type Response is not JSON serializable
08:19:52 PM: INFO [_internal.py:96] 127.0.0.1 - - [01/Dec/2023 20:19:52] "[35m[1mGET /api/task_lists HTTP/1.1[0m" 500 -
08:20:42 PM: INFO [_internal.py:96] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
08:20:42 PM: INFO [_internal.py:96] [33mPress CTRL+C to quit[0m
08:20:42 PM: INFO [_internal.py:96]  * Restarting with stat
08:20:42 PM: WARNING [_internal.py:96]  * Debugger is active!
08:20:42 PM: INFO [_internal.py:96]  * Debugger PIN: 133-926-406
08:21:07 PM: INFO [_internal.py:96]  * Detected change in '/home/yoaddan/RepositoriosDistribuidos/proyecto_backend/TASKLIST_API/TaskListAPI/app.py', reloading
08:21:07 PM: INFO [_internal.py:96]  * Restarting with stat
08:21:07 PM: WARNING [_internal.py:96]  * Debugger is active!
08:21:07 PM: INFO [_internal.py:96]  * Debugger PIN: 133-926-406
08:23:48 PM: CRITICAL [task_list_services.py:30] Error fetching all task lists from the database: 'Collection' object is not iterable
08:23:48 PM: ERROR [task_list_routes.py:25] Error fetching data from the database: Object of type Response is not JSON serializable
Traceback (most recent call last):
  File "/home/yoaddan/RepositoriosDistribuidos/proyecto_backend/TASKLIST_API/TaskListAPI/routes/task_list_routes.py", line 23, in get_task_lists
    return jsonify(self.task_lists), 200
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yoaddan/.local/lib/python3.11/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yoaddan/.local/lib/python3.11/site-packages/flask/json/provider.py", line 215, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=self.mimetype
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yoaddan/.local/lib/python3.11/site-packages/flask/json/provider.py", line 180, in dumps
    return json.dumps(obj, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/usr/lib64/python3.11/json/encoder.py", line 202, in encode
    chunks = list(chunks)
             ^^^^^^^^^^^^
  File "/usr/lib64/python3.11/json/encoder.py", line 430, in _iterencode
    yield from _iterencode_list(o, _current_indent_level)
  File "/usr/lib64/python3.11/json/encoder.py", line 326, in _iterencode_list
    yield from chunks
  File "/usr/lib64/python3.11/json/encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "/home/yoaddan/.local/lib/python3.11/site-packages/flask/json/provider.py", line 120, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type Response is not JSON serializable
08:23:48 PM: INFO [_internal.py:96] 127.0.0.1 - - [01/Dec/2023 20:23:48] "[35m[1mGET /api/task_lists HTTP/1.1[0m" 500 -
08:26:23 PM: INFO [_internal.py:96]  * Detected change in '/home/yoaddan/RepositoriosDistribuidos/proyecto_backend/TASKLIST_API/TaskListAPI/services/task_list_services.py', reloading
08:26:24 PM: INFO [_internal.py:96]  * Restarting with stat
08:26:24 PM: WARNING [_internal.py:96]  * Debugger is active!
08:26:24 PM: INFO [_internal.py:96]  * Debugger PIN: 133-926-406
08:26:51 PM: ERROR [task_list_routes.py:25] Error fetching data from the database: Object of type ObjectId is not JSON serializable
Traceback (most recent call last):
  File "/home/yoaddan/RepositoriosDistribuidos/proyecto_backend/TASKLIST_API/TaskListAPI/routes/task_list_routes.py", line 23, in get_task_lists
    return jsonify(self.task_lists), 200
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yoaddan/.local/lib/python3.11/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yoaddan/.local/lib/python3.11/site-packages/flask/json/provider.py", line 215, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=self.mimetype
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yoaddan/.local/lib/python3.11/site-packages/flask/json/provider.py", line 180, in dumps
    return json.dumps(obj, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/usr/lib64/python3.11/json/encoder.py", line 202, in encode
    chunks = list(chunks)
             ^^^^^^^^^^^^
  File "/usr/lib64/python3.11/json/encoder.py", line 430, in _iterencode
    yield from _iterencode_list(o, _current_indent_level)
  File "/usr/lib64/python3.11/json/encoder.py", line 326, in _iterencode_list
    yield from chunks
  File "/usr/lib64/python3.11/json/encoder.py", line 406, in _iterencode_dict
    yield from chunks
  File "/usr/lib64/python3.11/json/encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "/home/yoaddan/.local/lib/python3.11/site-packages/flask/json/provider.py", line 120, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type ObjectId is not JSON serializable
08:26:51 PM: INFO [_internal.py:96] 127.0.0.1 - - [01/Dec/2023 20:26:51] "[35m[1mGET /api/task_lists HTTP/1.1[0m" 500 -
08:27:35 PM: INFO [_internal.py:96]  * Detected change in '/home/yoaddan/RepositoriosDistribuidos/proyecto_backend/TASKLIST_API/TaskListAPI/services/task_list_services.py', reloading
08:27:35 PM: INFO [_internal.py:96]  * Restarting with stat
08:27:35 PM: WARNING [_internal.py:96]  * Debugger is active!
08:27:35 PM: INFO [_internal.py:96]  * Debugger PIN: 133-926-406
08:28:45 PM: INFO [_internal.py:96]  * Detected change in '/home/yoaddan/RepositoriosDistribuidos/proyecto_backend/TASKLIST_API/TaskListAPI/services/task_list_services.py', reloading
08:28:45 PM: INFO [_internal.py:96]  * Restarting with stat
08:28:46 PM: WARNING [_internal.py:96]  * Debugger is active!
08:28:46 PM: INFO [_internal.py:96]  * Debugger PIN: 133-926-406
08:28:56 PM: INFO [_internal.py:96] 127.0.0.1 - - [01/Dec/2023 20:28:56] "[35m[1mGET /api/task_lists HTTP/1.1[0m" 500 -
08:37:49 PM: INFO [_internal.py:96]  * Detected change in '/home/yoaddan/RepositoriosDistribuidos/proyecto_backend/TASKLIST_API/TaskListAPI/routes/task_list_routes.py', reloading
08:37:50 PM: INFO [_internal.py:96]  * Restarting with stat
08:37:50 PM: WARNING [_internal.py:96]  * Debugger is active!
08:37:50 PM: INFO [_internal.py:96]  * Debugger PIN: 133-926-406
08:37:58 PM: ERROR [task_list_routes.py:25] Error fetching data from the database: Object of type ObjectId is not JSON serializable
Traceback (most recent call last):
  File "/home/yoaddan/RepositoriosDistribuidos/proyecto_backend/TASKLIST_API/TaskListAPI/routes/task_list_routes.py", line 23, in get_task_lists
    return jsonify({'data':self.task_lists}), 200
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yoaddan/.local/lib/python3.11/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yoaddan/.local/lib/python3.11/site-packages/flask/json/provider.py", line 215, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=self.mimetype
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yoaddan/.local/lib/python3.11/site-packages/flask/json/provider.py", line 180, in dumps
    return json.dumps(obj, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/usr/lib64/python3.11/json/encoder.py", line 202, in encode
    chunks = list(chunks)
             ^^^^^^^^^^^^
  File "/usr/lib64/python3.11/json/encoder.py", line 432, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib64/python3.11/json/encoder.py", line 406, in _iterencode_dict
    yield from chunks
  File "/usr/lib64/python3.11/json/encoder.py", line 326, in _iterencode_list
    yield from chunks
  File "/usr/lib64/python3.11/json/encoder.py", line 406, in _iterencode_dict
    yield from chunks
  File "/usr/lib64/python3.11/json/encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "/home/yoaddan/.local/lib/python3.11/site-packages/flask/json/provider.py", line 120, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type ObjectId is not JSON serializable
08:37:58 PM: INFO [_internal.py:96] 127.0.0.1 - - [01/Dec/2023 20:37:58] "[35m[1mGET /api/task_lists HTTP/1.1[0m" 500 -
08:41:00 PM: INFO [_internal.py:96] 127.0.0.1 - - [01/Dec/2023 20:41:00] "GET /api/task_lists HTTP/1.1" 200 -
08:57:32 PM: INFO [_internal.py:96]  * Detected change in '/home/yoaddan/RepositoriosDistribuidos/proyecto_backend/TASKLIST_API/TaskListAPI/app.py', reloading
08:57:32 PM: INFO [_internal.py:96]  * Restarting with stat
08:57:32 PM: WARNING [_internal.py:96]  * Debugger is active!
08:57:32 PM: INFO [_internal.py:96]  * Debugger PIN: 133-926-406
08:58:26 PM: INFO [_internal.py:96] 127.0.0.1 - - [01/Dec/2023 20:58:26] "GET /api/task_lists HTTP/1.1" 200 -
09:04:12 PM: INFO [_internal.py:96] 127.0.0.1 - - [01/Dec/2023 21:04:12] "GET /api/task_lists HTTP/1.1" 200 -
09:07:12 PM: INFO [_internal.py:96]  * Detected change in '/home/yoaddan/RepositoriosDistribuidos/proyecto_backend/TASKLIST_API/TaskListAPI/routes/task_list_routes.py', reloading
09:07:13 PM: INFO [_internal.py:96]  * Restarting with stat
09:07:13 PM: WARNING [_internal.py:96]  * Debugger is active!
09:07:13 PM: INFO [_internal.py:96]  * Debugger PIN: 133-926-406
09:07:27 PM: INFO [_internal.py:96] 127.0.0.1 - - [01/Dec/2023 21:07:27] "GET /api/task_lists HTTP/1.1" 200 -
09:16:40 PM: INFO [_internal.py:96]  * Detected change in '/home/yoaddan/RepositoriosDistribuidos/proyecto_backend/TASKLIST_API/TaskListAPI/routes/task_list_routes.py', reloading
09:16:40 PM: INFO [_internal.py:96]  * Restarting with stat
09:16:41 PM: WARNING [_internal.py:96]  * Debugger is active!
09:16:41 PM: INFO [_internal.py:96]  * Debugger PIN: 133-926-406
09:16:48 PM: ERROR [task_list_routes.py:26] Error getting data from the database: 'int' object is not callable
Traceback (most recent call last):
  File "/home/yoaddan/RepositoriosDistribuidos/proyecto_backend/TASKLIST_API/TaskListAPI/routes/task_list_routes.py", line 23, in get_task_lists
    log.INFO('Succesful request, fetched task lists')
TypeError: 'int' object is not callable
09:16:48 PM: INFO [_internal.py:96] 127.0.0.1 - - [01/Dec/2023 21:16:48] "[35m[1mGET /api/task_lists HTTP/1.1[0m" 500 -
09:18:18 PM: INFO [_internal.py:96]  * Detected change in '/home/yoaddan/RepositoriosDistribuidos/proyecto_backend/TASKLIST_API/TaskListAPI/routes/task_list_routes.py', reloading
09:18:18 PM: INFO [_internal.py:96]  * Restarting with stat
09:18:19 PM: WARNING [_internal.py:96]  * Debugger is active!
09:18:19 PM: INFO [_internal.py:96]  * Debugger PIN: 133-926-406
09:18:23 PM: INFO [task_list_routes.py:23] Succesful request, fetched task lists
09:18:23 PM: INFO [_internal.py:96] 127.0.0.1 - - [01/Dec/2023 21:18:23] "GET /api/task_lists HTTP/1.1" 200 -
09:21:04 PM: INFO [task_list_routes.py:23] Succesful request, fetched task lists
09:21:04 PM: INFO [_internal.py:96] 127.0.0.1 - - [01/Dec/2023 21:21:04] "GET /api/task_lists HTTP/1.1" 200 -
09:24:06 PM: INFO [_internal.py:96]  * Detected change in '/home/yoaddan/RepositoriosDistribuidos/proyecto_backend/TASKLIST_API/TaskListAPI/routes/task_list_routes.py', reloading
09:24:06 PM: INFO [_internal.py:96]  * Restarting with stat
09:25:23 PM: INFO [_internal.py:96] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.18:5000
09:25:23 PM: INFO [_internal.py:96] [33mPress CTRL+C to quit[0m
09:25:23 PM: INFO [_internal.py:96]  * Restarting with stat
09:25:24 PM: WARNING [_internal.py:96]  * Debugger is active!
09:25:24 PM: INFO [_internal.py:96]  * Debugger PIN: 133-926-406
09:25:30 PM: INFO [task_list_routes.py:24] [TASKLISTS_ROUTES] Succesful request, fetched task lists
09:25:30 PM: INFO [_internal.py:96] 127.0.0.1 - - [01/Dec/2023 21:25:30] "GET /api/task_lists HTTP/1.1" 200 -
09:30:47 PM: INFO [_internal.py:96]  * Detected change in '/home/yoaddan/RepositoriosDistribuidos/proyecto_backend/TASKLIST_API/TaskListAPI/routes/task_list_routes.py', reloading
09:30:47 PM: INFO [_internal.py:96]  * Restarting with stat
09:30:48 PM: WARNING [_internal.py:96]  * Debugger is active!
09:30:48 PM: INFO [_internal.py:96]  * Debugger PIN: 133-926-406
09:30:53 PM: INFO [task_list_routes.py:24] [91m[TASKLISTS_ROUTES][0m Succesful request, fetched task lists
09:30:53 PM: INFO [_internal.py:96] 127.0.0.1 - - [01/Dec/2023 21:30:53] "GET /api/task_lists HTTP/1.1" 200 -
09:32:56 PM: INFO [_internal.py:96]  * Detected change in '/home/yoaddan/RepositoriosDistribuidos/proyecto_backend/TASKLIST_API/TaskListAPI/logger/logger_base.py', reloading
09:32:56 PM: INFO [_internal.py:96]  * Restarting with stat
09:32:57 PM: WARNING [91m[_internal.py:96][0m  * Debugger is active!
09:32:57 PM: INFO [91m[_internal.py:96][0m  * Debugger PIN: 133-926-406
09:34:55 PM: INFO [91m[_internal.py:96][0m  * Detected change in '/home/yoaddan/RepositoriosDistribuidos/proyecto_backend/TASKLIST_API/TaskListAPI/logger/logger_base.py', reloading
09:34:55 PM: INFO [_internal.py:96]  * Restarting with stat
09:34:56 PM: WARNING [93m[_internal.py:96][0m  * Debugger is active!
09:34:56 PM: INFO [93m[_internal.py:96][0m  * Debugger PIN: 133-926-406
09:35:25 PM: INFO [93m[_internal.py:96][0m  * Detected change in '/home/yoaddan/RepositoriosDistribuidos/proyecto_backend/TASKLIST_API/TaskListAPI/logger/logger_base.py', reloading
09:35:25 PM: INFO [_internal.py:96]  * Restarting with stat
09:35:26 PM: WARNING [96m[_internal.py:96][0m  * Debugger is active!
09:35:26 PM: INFO [96m[_internal.py:96][0m  * Debugger PIN: 133-926-406
09:35:55 PM: INFO [96m[_internal.py:96][0m  * Detected change in '/home/yoaddan/RepositoriosDistribuidos/proyecto_backend/TASKLIST_API/TaskListAPI/logger/logger_base.py', reloading
09:35:55 PM: INFO [_internal.py:96]  * Restarting with stat
09:35:56 PM: WARNING [92m[_internal.py:96][0m  * Debugger is active!
09:35:56 PM: INFO [92m[_internal.py:96][0m  * Debugger PIN: 133-926-406
09:36:47 PM: INFO [92m[_internal.py:96][0m  * Detected change in '/home/yoaddan/RepositoriosDistribuidos/proyecto_backend/TASKLIST_API/TaskListAPI/logger/logger_base.py', reloading
09:36:47 PM: INFO [_internal.py:96]  * Restarting with stat
09:36:48 PM: WARNING [93m[_internal.py:96][0m  * Debugger is active!
09:36:48 PM: INFO [93m[_internal.py:96][0m  * Debugger PIN: 133-926-406
09:37:13 PM: INFO [93m[_internal.py:96][0m  * Detected change in '/home/yoaddan/RepositoriosDistribuidos/proyecto_backend/TASKLIST_API/TaskListAPI/logger/logger_base.py', reloading
09:37:14 PM: INFO [_internal.py:96]  * Restarting with stat
09:37:14 PM: WARNING [93m[_internal.py:[91m96[0m][0m  * Debugger is active!
09:37:14 PM: INFO [93m[_internal.py:[91m96[0m][0m  * Debugger PIN: 133-926-406
09:37:44 PM: INFO [93m[_internal.py:[91m96[0m][0m  * Detected change in '/home/yoaddan/RepositoriosDistribuidos/proyecto_backend/TASKLIST_API/TaskListAPI/logger/logger_base.py', reloading
09:37:45 PM: INFO [_internal.py:96]  * Restarting with stat
09:37:45 PM: WARNING [93m[_internal.py:[91m96[0m[93m[][0m  * Debugger is active!
09:37:45 PM: INFO [93m[_internal.py:[91m96[0m[93m[][0m  * Debugger PIN: 133-926-406
09:37:56 PM: INFO [93m[_internal.py:[91m96[0m[93m[][0m  * Detected change in '/home/yoaddan/RepositoriosDistribuidos/proyecto_backend/TASKLIST_API/TaskListAPI/logger/logger_base.py', reloading
09:37:57 PM: INFO [_internal.py:96]  * Restarting with stat
09:37:57 PM: WARNING [93m[_internal.py:[91m96[0m[93m][0m  * Debugger is active!
09:37:57 PM: INFO [93m[_internal.py:[91m96[0m[93m][0m  * Debugger PIN: 133-926-406
09:39:24 PM: INFO [93m[_internal.py:[91m96[0m[93m][0m  * Detected change in '/home/yoaddan/RepositoriosDistribuidos/proyecto_backend/TASKLIST_API/TaskListAPI/logger/logger_base.py', reloading
09:39:24 PM: INFO [_internal.py:96]  * Restarting with stat
09:44:48 PM: INFO [_internal.py:96]  * Restarting with stat
09:45:03 PM: INFO [_internal.py:96]  * Restarting with stat
09:45:04 PM: WARNING [93m[_internal.py:[91m96[0m[93m][0m  * Debugger is active!
09:45:04 PM: INFO [93m[_internal.py:[91m96[0m[93m][0m  * Debugger PIN: 133-926-406
09:47:22 PM: INFO [93m[_internal.py:[91m96[0m[93m][0m  * Detected change in '/home/yoaddan/RepositoriosDistribuidos/proyecto_backend/TASKLIST_API/TaskListAPI/logger/logger_base.py', reloading
09:47:23 PM: INFO [_internal.py:96]  * Restarting with stat
09:47:47 PM: INFO [_internal.py:96]  * Restarting with stat
09:47:57 PM: INFO [_internal.py:96]  * Restarting with stat
09:47:58 PM: WARNING [93m[_internal.py:[91m96[0m[93m][0m  * Debugger is active!
09:47:58 PM: INFO [93m[_internal.py:[91m96[0m[93m][0m  * Debugger PIN: 133-926-406
09:48:11 PM: INFO [93m[task_list_routes.py:[91m23[0m[93m][0m Succesful request, fetched task lists
09:48:11 PM: INFO [93m[_internal.py:[91m96[0m[93m][0m 127.0.0.1 - - [01/Dec/2023 21:48:11] "GET /api/task_lists HTTP/1.1" 200 -
09:54:48 PM: INFO [93m[task_list_routes.py:[91m23[0m[93m][0m Succesful request, fetched task lists
09:54:48 PM: INFO [93m[_internal.py:[91m96[0m[93m][0m 127.0.0.1 - - [01/Dec/2023 21:54:48] "GET /api/task_lists HTTP/1.1" 200 -
09:57:13 PM: INFO [93m[_internal.py:[91m96[0m[93m][0m  * Detected change in '/home/yoaddan/RepositoriosDistribuidos/proyecto_backend/TASKLIST_API/TaskListAPI/logger/logger_base.py', reloading
09:57:13 PM: INFO [_internal.py:96]  * Restarting with stat
09:57:14 PM: WARNING [93m[_internal.py:[91m96[0m[93m][0m  * Debugger is active!
09:57:14 PM: INFO [93m[_internal.py:[91m96[0m[93m][0m  * Debugger PIN: 133-926-406
10:00:17 PM: INFO [93m[_internal.py:[91m96[0m[93m][0m  * Detected change in '/home/yoaddan/RepositoriosDistribuidos/proyecto_backend/TASKLIST_API/TaskListAPI/logger/logger_base.py', reloading
10:00:18 PM: INFO [_internal.py:96]  * Restarting with stat
10:00:18 PM: WARNING [93m[_internal.py:[91m96[0m[93m][0m  * Debugger is active!
10:00:18 PM: INFO [93m[_internal.py:[91m96[0m[93m][0m  * Debugger PIN: 133-926-406
10:08:52 PM: INFO [93m[_internal.py:[91m96[0m[93m][0m  * Detected change in '/home/yoaddan/RepositoriosDistribuidos/proyecto_backend/TASKLIST_API/TaskListAPI/services/task_list_services.py', reloading
10:08:52 PM: INFO [_internal.py:96]  * Restarting with stat
10:08:53 PM: WARNING [93m[_internal.py:[91m96[0m[93m][0m  * Debugger is active!
10:08:53 PM: INFO [93m[_internal.py:[91m96[0m[93m][0m  * Debugger PIN: 133-926-406
10:16:54 PM: INFO [93m[_internal.py:[91m96[0m[93m][0m  * Detected change in '/home/yoaddan/RepositoriosDistribuidos/proyecto_backend/TASKLIST_API/TaskListAPI/services/task_list_services.py', reloading
10:16:55 PM: INFO [_internal.py:96]  * Restarting with stat
10:16:56 PM: WARNING [93m[_internal.py:[91m96[0m[93m][0m  * Debugger is active!
10:16:56 PM: INFO [93m[_internal.py:[91m96[0m[93m][0m  * Debugger PIN: 133-926-406
11:09:49 PM: INFO [93m[_internal.py:[91m96[0m[93m][0m [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.18:5000
11:09:49 PM: INFO [93m[_internal.py:[91m96[0m[93m][0m [33mPress CTRL+C to quit[0m
11:09:49 PM: INFO [93m[_internal.py:[91m96[0m[93m][0m  * Restarting with stat
11:09:49 PM: WARNING [93m[_internal.py:[91m96[0m[93m][0m  * Debugger is active!
11:09:49 PM: INFO [93m[_internal.py:[91m96[0m[93m][0m  * Debugger PIN: 142-548-151
11:24:38 PM: INFO [93m[_internal.py:[91m96[0m[93m][0m  * Detected change in '/home/yoaddan/RepositoriosDistribuidos/proyecto_backend/TASKLIST_API/TaskListAPI/schemas/task_list_schemas.py', reloading
11:24:39 PM: INFO [93m[_internal.py:[91m96[0m[93m][0m  * Restarting with stat
11:24:42 PM: WARNING [93m[_internal.py:[91m96[0m[93m][0m  * Debugger is active!
11:24:42 PM: INFO [93m[_internal.py:[91m96[0m[93m][0m  * Debugger PIN: 142-548-151
11:24:49 PM: INFO [93m[task_list_routes.py:[91m43[0m[93m][0m Succesful request, fetched task lists
11:24:49 PM: INFO [93m[_internal.py:[91m96[0m[93m][0m 127.0.0.1 - - [01/Dec/2023 23:24:49] "GET /api/task_lists HTTP/1.1" 200 -
11:38:05 PM: INFO [93m[_internal.py:[91m96[0m[93m][0m  * Detected change in '/home/yoaddan/RepositoriosDistribuidos/proyecto_backend/TASKLIST_API/TaskListAPI/routes/task_list_routes.py', reloading
11:38:06 PM: INFO [93m[_internal.py:[91m96[0m[93m][0m  * Restarting with stat
11:38:06 PM: WARNING [93m[_internal.py:[91m96[0m[93m][0m  * Debugger is active!
11:38:06 PM: INFO [93m[_internal.py:[91m96[0m[93m][0m  * Debugger PIN: 142-548-151
